# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TPOv1', '0003_auto_20170322_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='drive_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
