# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.CharField(max_length=200)),
                ('Suggestions', models.TextField()),
            ],
        ),
    ]
