# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wonAt', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=50)),
                ('wonOn', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateType', models.CharField(choices=[('Participated', 'Participated'), ('Attended', 'Attended'), ('Volunteered', 'Volunteered'), ('Won', 'Won'), ('Conducted', 'Conducted'), ('Co-ordinated', 'Co-ordinated')], max_length=13)),
                ('event', models.CharField(max_length=30)),
                ('heldOn', models.DateField()),
                ('heldAt', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_rollno', models.CharField(max_length=12)),
                ('stu_firstname', models.CharField(max_length=30)),
                ('stu_lastame', models.CharField(max_length=30)),
                ('stu_streetAddress', models.CharField(max_length=100)),
                ('stu_city', models.CharField(max_length=20)),
                ('stu_district', models.CharField(max_length=20)),
                ('stu_state', models.CharField(max_length=20)),
                ('stu_pincode', models.IntegerField()),
                ('stu_homephone', models.IntegerField()),
                ('stu_mobilephone', models.IntegerField()),
                ('stu_emailid', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEduQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=15)),
                ('institute', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
                ('yearOfPass', models.IntegerField()),
                ('marksObtained', models.IntegerField()),
                ('stu_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fathername', models.CharField(max_length=30)),
                ('stu_mothername', models.CharField(max_length=30)),
                ('stu_dob', models.DateField()),
                ('stu_maritalstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=7)),
                ('stu_hobbies', models.CharField(max_length=100)),
                ('stu_languagesknown', models.CharField(max_length=100)),
                ('stu_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('technologiesUsed', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=300)),
                ('stu_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('stu_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails')),
            ],
        ),
        migrations.AddField(
            model_name='studentcertifications',
            name='stu_rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails'),
        ),
        migrations.AddField(
            model_name='studentawards',
            name='stu_rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails'),
        ),
        migrations.AddField(
            model_name='studentactivities',
            name='stu_rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentContactDetails'),
        ),
    ]
