# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivities',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentawards',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentcertifications',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studenteduqualification',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentpersonal',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentprojects',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentskills',
            name='stu_rollno',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_city',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_district',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_emailid',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_homephone',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_lastame',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_mobilephone',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_pincode',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_state',
        ),
        migrations.RemoveField(
            model_name='studentcontactdetails',
            name='stu_streetAddress',
        ),
        migrations.DeleteModel(
            name='StudentActivities',
        ),
        migrations.DeleteModel(
            name='StudentAwards',
        ),
        migrations.DeleteModel(
            name='StudentCertifications',
        ),
        migrations.DeleteModel(
            name='StudentEduQualification',
        ),
        migrations.DeleteModel(
            name='StudentPersonal',
        ),
        migrations.DeleteModel(
            name='StudentProjects',
        ),
        migrations.DeleteModel(
            name='StudentSkills',
        ),
    ]
